spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_portal_prod
    username: produser
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  thymeleaf:
    cache: true
  profiles:
    active: prod
logging:
  level:
    root: WARN
    com.example.bookportal: INFO
